PREP(canSurrender);
PREP(collectSurrenderUnits);
PREP(surrenderToggle);
PREP(surrenderApply);
PREP(surrenderActionModifier);
PREP(registerSurrender);
PREP(captureTick);
PREP(captureUnit);
PREP(captureApply);
